### ISSUE TITLE
无法生成csv文件

### ISSUE THREAD

**Issue by xiaosaoba** [sn00pyd0g3/wechat-export#1]
能获取key，但是执行解密内容不能生成csv文件啊

**Comment by sn00pyd0g3** [comment]
@xiaosaoba 请提供复现步骤&wx版本。

**Comment by xiaosaoba** [comment]
![image](https://user-images.githubusercontent.com/26709924/187115542-0e193038-4093-4914-835f-9c40bbc89737.png)
![image](https://user-images.githubusercontent.com/26709924/187116049-4dcdd852-f80a-4e7d-977d-94d6d3841e9c.png)
![image](https://user-images.githubusercontent.com/26709924/187116130-40fe2fc4-9eab-47d5-8ecc-40a01799c950.png)

**Comment by sn00pyd0g3** [comment]
@xiaosaoba 你这里面没有消息记录的数据库，所以没有生成CSV。
目前CSV只会解析消息记录数据库（MSG0.DB，MSG1.db，...，MSGn.db）
别的数据库能解密，但不会导出成CSV，可以用navicat打开自己看。

**Comment by xiaosaoba** [comment]
找到消息记录数据库文件了，然后确实是可以生成消息记录的csv 多谢了~

**Comment by xiaosaoba** [comment]
手机端的消息记录数据库文件是什么格式？哪个名字的
